[2024-03-09T10:05:06.990+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: cron_expression_dag.simple_task scheduled__2024-03-07T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
